version: '3.8'

services:
  app:
    build: .
    container_name: sm-web3-energy_app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=1111
      - DB_DATABASE=database_contracts
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - webnet

  db:
    image: mysql:5.7
    container_name: sm-web3-energy_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database_contracts
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
    volumes:
      - db_data:/var/lib/mysql
      - ./db/database_contracts.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sm-web3-energy_phpmyadmin
    restart: always
    ports:
      - "6060:80"
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: 1111
    depends_on:
      - db
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  db_data:
